data_dir: ${p:/data/shared/cssb_data/openfold_distillation/rna_distillation_set/rna_monomer_preprocessed_cache}
file_pattern: "structure.npz"

env_path: ${p:/data/shared/cssb_data/openfold_distillation/lmdb/cif_rna.lmdb}

recipe: ${p:src/structcooker/workflows/ingest/openfold_structure.py}

n_jobs: -1
chunk_size: 10000
test_run: true

key_builder: structcooker.instructions.readers.openfold.openfold_entry_key

reader:
  loader: structcooker.instructions.readers.openfold.get_openfold_structure_data

writer:
  serializer: structcooker.instructions.transforms.codecs.to_bytes
