# db extract
db_path: ${p:/public_data02/BioMolDB_20260224/cif_attached_valid_2.lmdb}
extract_recipe_path: ${p:src/structcooker/workflows/analysis/db_profile.py}
output_data_path: ${p:/public_data02/BioMolDB_20260224/metadata/valid2_summary.csv}

reader:
  adapter: structcooker.instructions.transforms.cifmol.convert_to_cifmol_attached_transformed
  deserializer: structcooker.instructions.transforms.codecs.from_bytes

writer:
  materializer: structcooker.instructions.writers.projections.write_statistics
