# rebuild
old_env_path: ${p:/data/psk6950/BioMolDB_20260224/a3m.lmdb}
new_env_path: ${p:/data/psk6950/BioMolDB_20260224/a3m_4k.lmdb}

recipe: ${p:src/structcooker/workflows/filters/a3m.py}


n_jobs: -1
chunk_size: 10000

reader:
  adapter: structcooker.instructions.readers.a3m.convert_to_msa_container
  deserializer: structcooker.instructions.transforms.codecs.from_bytes

writer:
  serializer: structcooker.instructions.transforms.codecs.to_bytes
