inputs: 
  data_dir: ${p:/data/psk6950/msa/}
  output_dir: ${p:/data/psk6950/msa_wo_lower/}
  output_pattern: ".a3m"
split_recipe_path: ${p:src/structcooker/workflows/search/load_a3m_list.py}
recipe_path: ${p:src/structcooker/workflows/filters/a3m_cleanup.py}
n_jobs: -1 # total 80 CPUs, 4 CPUs per job for HHblits
test_run: false
