# rebuild
old_env_path: ${p:/public_data02/BioMolDB_test/cif.lmdb}
new_env_path: ${p:/public_data02/BioMolDB_test/cif_train_20210930_resolution9_residue10k_chain300.lmdb}

recipe: ${p:src/structcooker/workflows/data_filter.py}
metadata_recipe: ${p:src/structcooker/workflows/load_signalp.py}

metadata_input:
  signalp_dir: ${p:/public_data02/BioMolDB_20260224/signalp}
  seqid2seq_path: ${p:/public_data02/BioMolDB_20260224/metadata/seq_id_map.tsv}

parameters:
  resolution_cutoff: 9.0
  max_token_count: 10240
  max_polymer_chain_count: 300
  start_date: null
  end_date: 2021-09-30

n_jobs: -1
chunk_size: 20000

reader:
  adapter: structcooker.readers.cifmol.convert_to_cifmol_dict
  deserializer: structcooker.codecs.from_bytes

writer:
  serializer: structcooker.codecs.to_bytes
