data_dir: ${p:/data/shared/cssb_data/openfold_distillation/sample100/rna}
file_pattern: "alignment.npz"

env_path: ${p:/data/shared/cssb_data/openfold_distillation/lmdb_sample/msa_rna.lmdb}

recipe: ${p:src/structcooker/workflows/ingest/openfold_msa.py}

n_jobs: -1
chunk_size: 10000
test_run: true

key_builder: structcooker.instructions.readers.openfold.openfold_entry_key

inputs:
  a3m_type: rna
  max_depth: null

reader:
  loader: structcooker.instructions.readers.openfold.get_openfold_msa_data

writer:
  serializer: structcooker.instructions.transforms.codecs.to_bytes
