# rebuild
old_env_path: ${p:/public_data02/BioMolDB_test/cif_train_20260224_resolution9_residue10k_chain300.lmdb}
new_env_path: ${p:/public_data02/BioMolDB_test/cif_attached_train_20260224_res9_chain300.lmdb}

recipe: ${p:src/structcooker/workflows/metadata/attach.py}
metadata_recipe: ${p:src/structcooker/workflows/metadata/load_sequence_metadata.py}

metadata_input:
  raw_fasta_path: ${p:/public_data02/BioMolDB_test/fasta/merged.fasta}
  seqid2seq_path: ${p:/public_data02/BioMolDB_test/metadata/seq_id_map.tsv}
  seqcluster_path: ${p:/public_data02/BioMolDB_test/metadata/seq_cluster30.tsv}


n_jobs: -1
chunk_size: 10000

reader:
  adapter: structcooker.instructions.transforms.cifmol.convert_to_cifmol_transformed
  deserializer: structcooker.instructions.transforms.codecs.from_bytes

writer:
  serializer: structcooker.instructions.transforms.codecs.to_bytes
