db_path: ${p:/public_data02/BioMolDB_test/cif_valid_1.lmdb}
extract_recipe_path: ${p:src/structcooker/workflows/exports/tv_fasta.py}
output_data_path: ${p:/public_data02/BioMolDB_test/fasta/valid_1.fasta}

reader:
  deserializer: structcooker.instructions.transforms.codecs.from_bytes

writer:
  materializer: structcooker.instructions.writers.projections.write_fasta
