# rebuild
old_env_path: ${p:/public_data02/BioMolDB_20260224/cif_train.lmdb}
new_env_path: ${p:/public_data02/BioMolDB_20260224/cif_attached_train.lmdb}

recipe: ${p:pipelines/recipe/attach_metadata.py}
metadata_recipe: ${p:pipelines/recipe/load_seq_metadata.py}

metadata_input:
  raw_fasta_path: ${p:/public_data02/BioMolDB_20260224/fasta/merged.fasta}
  seqid2seq_path: ${p:/public_data02/BioMolDB_20260224/metadata/seq_id_map.tsv}
  seqcluster_path: ${p:/public_data02/BioMolDB_20260224/metadata/seq_cluster30.tsv}

convert_func: pipelines.transforms.cifmol_transforms.convert_to_cifmol_transformed

n_jobs: -1
chunk_size: 10000
