# rebuild
old_env_path: ${p:/home/psk6950/data/StructSticklerDB/cif_valid_1.lmdb}
new_env_path: ${p:/home/psk6950/data/StructSticklerDB/cif_attached_valid_1.lmdb}

recipe: ${p:pipelines/recipe/attach_metadata.py}
metadata_recipe: ${p:pipelines/recipe/load_seq_metadata.py}

metadata_input:
  raw_fasta_path: ${p:/home/psk6950/data/StructSticklerDB/fasta/merged.fasta}
  seqid2seq_path: ${p:/home/psk6950/data/StructSticklerDB/metadata/seq_id_map.tsv}
  seqcluster_path: ${p:/home/psk6950/data/StructSticklerDB/metadata/seq_cluster30.tsv}

convert_func: pipelines.transforms.cifmol_transforms.convert_to_cifmol_transformed

n_jobs: -1
chunk_size: 10000
