# rebuild
old_env_path: ${p:/public_data02/BioMolDB_test/cif.lmdb}
new_env_path: ${p:/public_data02/BioMolDB_test/cif_disordered_to_predict.lmdb}

recipe: ${p:src/structcooker/workflows/disordered_data_filter.py}
metadata_recipe: ${p:src/structcooker/workflows/load_signalp.py}

metadata_input:
  signalp_dir: ${p:/public_data02/BioMolDB_20260224/signalp}
  seqid2seq_path: ${p:/public_data02/BioMolDB_20260224/metadata/seq_id_map.tsv}

parameters:
  resolution_cutoff: 4.5
  min_unresolved_residues: 40
  min_token_count: 256
  max_token_count: 2560
  min_protein_chain_count: 1
  max_polymer_chain_count: 48
  start_date: null
  end_date: 2026-03-01

n_jobs: -1
chunk_size: 20000

reader:
  adapter: structcooker.readers.cifmol.convert_to_cifmol_dict
  deserializer: structcooker.codecs.from_bytes

writer:
  serializer: structcooker.codecs.to_bytes
