# db extract
db_path: ${p:/public_data02/BioMolDB_20260224/cif_attached_valid_2.lmdb}
convert_func: pipelines.transforms.cifmol_transforms.convert_to_cifmol_attached_transformed
extract_recipe_path: ${p:/home/psk6950/practice/StructCooker/pipelines/recipe/extract_node_and_edge.py}
project_func: pipelines.projection.projections.write_edge_node
output_data_path: ${p:/public_data02/BioMolDB_20260224/metadata/valid2_edge_node.tsv}