# db extract
db_path: ${p:/public_data02/BioMolDB_test/cif_attached_disordered.lmdb}
extract_recipe_path: ${p:/home/psk6950/practice/StructCooker/pipelines/recipe/extract_node_and_edge.py}
output_data_path: ${p:/public_data02/BioMolDB_test/metadata/disordered_edge_node.tsv}

reader:
  adapter: pipelines.transforms.cifmol_transforms.convert_to_cifmol_attached_transformed
  deserializer: pipelines.utils.convert.from_bytes

writer:
  materializer: pipelines.projection.projections.write_edge_node
