db_path: ${p:/public_data02/BioMolDB_test/cif_valid_1.lmdb}
extract_recipe_path: ${p:/home/psk6950/practice/StructCooker/pipelines/recipe/extract_tv_fasta.py}
output_data_path: ${p:/public_data02/BioMolDB_test/fasta/valid_1.fasta}

reader:
  deserializer: pipelines.utils.convert.from_bytes

writer:
  materializer: pipelines.projection.projections.write_fasta
