db_path: ${p:/home/psk6950/data/StructSticklerDB/cif_train.lmdb}
extract_recipe_path: ${p:/home/psk6950/StructStickler/pipelines/recipe/extract_tv_fasta.py}
project_func: pipelines.projection.projections.write_fasta
output_data_path: ${p:/home/psk6950/data/StructSticklerDB/fasta/train.fasta}
