db_path: ${p:/home/psk6950/data/BioMolDBv2_2024Oct21/cif_raw.lmdb}
extract_recipe_path: ${p:/home/psk6950/StructStickler/pipelines/recipe/extract_metadata.py}
project_func: pipelines.projection.projections.write_metadata
output_data_path: ${p:/home/psk6950/data/StructSticklerDB/metadata/cif_metadata.tsv}
