inputs: 
  db_template: ${p:/data/psk6950/template_db/pdb100_20260224/pdb100_20260224}
  hhsuite_bin_dir: ${p:/home/psk6950/bin/}
  cpu_per_job: 4
  mem_per_job: 16 # in GB, total
  input_dir: ${p:/data/psk6950/msa/}
  output_dir: ${p:/data/psk6950/hhr/}
  output_pattern: ".hhr"
split_recipe_path: ${p:/home/psk6950/StructCooker/pipelines/recipe/load_a3m_list.py}
recipe_path: ${p:/home/psk6950/StructCooker/pipelines/recipe/hhsearch.py}
n_jobs: 28 # total 80 CPUs, 4 CPUs per job for HHblits
test_run: false
