inputs: 
  input_dir: ${p:/data/psk6950/msa/}
  output_dir: ${p:/data/psk6950/msa_wo_lower/}
  output_pattern: ".a3m"
split_recipe_path: ${p:/home/psk6950/StructCooker/pipelines/recipe/load_a3m_list.py}
recipe_path: ${p:/home/psk6950/StructCooker/pipelines/recipe/remove_lower_from_a3m.py}
n_jobs: -1 # total 80 CPUs, 4 CPUs per job for HHblits
test_run: false
