# rebuild
old_env_path: ${p:/public_data02/BioMolDB_20260224/cif_raw.lmdb}
new_env_path: ${p:/public_data02/BioMolDB_20260224/cif_valid_1.lmdb}

recipe: ${p:pipelines/recipe/valid_filter_1.py}
metadata_recipe: ${p:pipelines/recipe/load_signalp.py}

metadata_input:
  signalp_dir: ${p:/public_data02/BioMolDB_20260224/signalp}
  seqid2seq_path: ${p:/public_data02/BioMolDB_20260224/metadata/seq_id_map.tsv}

convert_func: pipelines.transforms.cifmol_transforms.convert_to_cifmol_dict
parameters:
  resolution_cutoff: 4.5
  max_token_count: 2560
  max_polymer_chain_count: 20
  start_date: 2021-09-30
  end_date: 2023-09-30

n_jobs: -1
chunk_size: 20000
